### ISSUE TITLE
SVGs not inlined when nested

### ISSUE THREAD

**Issue by vhogemann** [theGC/html-webpack-inline-svg-plugin#1]
Hi,

I'm using this plugin along with Hot Module Reload, and when HMR re-emits the HTML the SVG are not getting inlined.

Any insight on what might be causing this problem?

**Comment by theGC** [comment]
Can you provide any more info?

We have tested it with a number of HMR based projects and things work as expected, emitting the SVG inline each time. It sounds like something specific to your webpack config might be causing this but without a repo to test the build its difficult to say what.

**Comment by vhogemann** [comment]
Indeed, it was not HMR.

The problem is that I was trying to nest the <img inline src=""> inside a div tag, and then it fails to be inlined. I wanted to do that to be able to apply a display:none style to it.

I thought that was HMR because every time I changed the source template, the svg failed to be inlined, but it turns out that if I put it anywhere else than at the very top of the <body> tag it fails.

**Comment by theGC** [comment]
Ah ok, that's not something I've tested as yet. Will look to have a play and upload a fix as I can't think of any reason not to allow nesting the inlined assets.

**Comment by lukeheath** [comment]
Thanks for sharing this plugin! I'm running into the same issue - SVGs can't be nested or the plugin won't replace them. I poked around a bit and it looks like an issue with the recursion in `getInlineImage()` but I haven't been successful in correcting yet.

**Comment by zumwald** [comment]
@theGC @lukeheath - I looked into fixing, it turned in to less of a fix and more of a rewrite \_(-_-)_/

I kept going along that path, and my fork actually ditches the string manipulations for parse5 operations (less tricky index math, and iterates in O(1) rather than O(n)). Downside is parse5 refuses to serialize a broken html tree, for which there were tests for in the existing code - I wasn't sure of the use case for broken html so I removed those tests and added PNG inline support via inlining a base64 encoded data URI.

I opted to publish as separate package as it turned into a significant divergence from the scope of the existing project, but would be happy to merge back if you like the direction.

**Comment by theGC** [comment]
@zumwald thank you. I had a look at the PR yesterday and did notice it was quite a substantial bit of tweaking! :)

The broken html tests were for our companies specific needs - we require separate header and footer ejs files. Therefore we found that we didn't always have matching  opening / closing tags but still needed the plugin to process the SVGs.

I'll have a look over the PR today - my priority is the broken html so need to look at how we can combine that with nested SVGs.

**Comment by theGC** [comment]
latest version (0.2.0) allows for nested SVGs
