### ISSUE TITLE
outputPath is not used right

### ISSUE THREAD

**Issue by wizardnet972** [theGC/html-webpack-inline-svg-plugin#10]
outputPath is not used right.

let's say my html is:
```
<html><body><img inline src="assets/kiwi.svg"></body></html>
```
my project folder is that:
```
- dist
+ src
---- index.html
--+ assets
----- kiwi.svg
```

So the problem its goes to dist folder and to fix it I need to set in html:
`<html><body><img inline src="../assets/kiwi.svg"></body></html>`

The outputPath is 'dist' folder.

**Comment by theGC** [comment]
this looks like the expected behaviour for the plugin. If you want to reference files from the root of your project you'll need to set **runPreEmit**:

```javascript
plugins: [
    new HtmlWebpackPlugin(),
    new HtmlWebpackInlineSVGPlugin({
        runPreEmit: true,
    })
]
```

[#setting-runpreemit-option](https://github.com/theGC/html-webpack-inline-svg-plugin#setting-runpreemit-option)

If you don't set **runPreEmit** then the plugin will grab the `<img>` tags **src** attribute after everything has been saved to the `dist` directory, and then try and find that file relative to `index.html`. Therefore if you have loaders running on `index.html` they may have updated the **src** attribute for you already, if not as you found, it will need to be set appropriately for when it resides within the `dist` directory.
