### ISSUE TITLE
Are <symbol> elements in SVGs supported?

### ISSUE THREAD

**Issue by mateatslc** [theGC/html-webpack-inline-svg-plugin#12]
I'm using icon sprites with `<symbol>` elements as described here:
https://css-tricks.com/svg-symbol-good-choice-icons/

Traditional SVGs work fine, but when I'm trying to inline such sprites they simply do not show up in the output. Any idea?

**Comment by theGC** [comment]
That's actually the main reason I created the project as we were using SVGs with symbols and wanted to get them into the output. There isn't a specific test for them though, albeit I use them myself and they work fine.

I'll see if adding one and testing for them throws up any errors.

**Comment by theGC** [comment]
Just had another look at the jasmine tests and there is actually a test using svg `symbols` and this file:

[https://raw.githubusercontent.com/theGC/html-webpack-inline-svg-plugin/master/spec/fixtures/images/moods.svg](moods.svg)

As this works I can only assume something within your project is causing the issue, not the plugin. If you double check the `<img>` tag has an **inline** attribute and the svg has the correct extension (.svg). Then so long as the plugin is installed and being called within your webpack settings it should be able to output the symbols just fine.

If you ping me a link to a repo I could have a quick look for anything else, otherwise, I'm not too sure what to suggest.

**Comment by mateatslc** [comment]
Looking at the SVG you linked, mine is missing the `<defs>` tag for sure. Will take a closer look...

**Comment by mateatslc** [comment]
Tracked it down. Looks like `style="display: none;"` on my `<svg>` tags is what derailing it.
Switched to `style="width: 0; height: 0; position: absolute; overflow: hidden;"` and works now.

**Comment by theGC** [comment]
cool, glad to here you sorted it
