### ISSUE TITLE
bizarro death with undefined

### ISSUE THREAD

**Issue by httpete** [theGC/html-webpack-inline-svg-plugin#14]
I have been using this with the runPreEmit option true for a while. Mysteriously, after a hard clean (some downstream dep must have moved) webpack just dies with a red "undefined". If  I remove this plugin it works fine.

**Comment by MethodGrab** [comment]
I encountered this as well.
For me, it was caused by a parse error in my SVG file.
SVGO failed but the error was a string, not an object with a `.message` property which this plugin was expecting. Changing [index.js#L493](https://github.com/theGC/html-webpack-inline-svg-plugin/blob/1.2.4/index.js#L493) to `.catch((err) => console.log(chalk.red(err)))` will show the correct error rather than `undefined`.

**Comment by theGC** [comment]
updated in v2.0.0 - @MethodGrab thanks for the fix
