### ISSUE TITLE
img tags are not replace in output file

### ISSUE THREAD

**Issue by royalrex** [theGC/html-webpack-inline-svg-plugin#36]
I want to integrate this plugin in my webpack pipeline, but I just can't get it to replace the img tags.

Webpack 4.44.2
html-loader 1.11.0
html-webpack-inline-svg-plugin 2.3.0
html-webpack-plugin 4.5.0

if I don't include a rule for loading svg's the plugin fails. So I use the file-loader for that.

```
      { 
        test: /\.svg$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              emitFile: false
            }
          },
        ], 
      },
```

I have included the plugin:
```
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: 'src/index-template.ejs',
      inject: 'body',
      APP_TIMESTAMP: '',
      SCRIPTS: scripts,
      CSS: css,
    }),
    new HtmlWebpackInlineSVGPlugin(),
```
and I can confirm that the plugin is run, it just doesn't do anything to the output.

The result is just the file-loader taking over and replacing the svg urls with the loaded file names.

Thank you for your time!

Best
Sebbe

**Comment by AntonioRedondo** [comment]
Hi @royalrex,

You shouldn't need the `file-loader` applied to the SVG extension on your webpack config in order for `html-webpack-inline-svg-plugin` to inline SVGs.

First the basics. Probably you're already doing this right. But just in case:
- Can you make sure you're adding the `inline` attribute to the `<img>` elements you want to inline?
- Or, can you make sure you're using the [`inlineAll`](HtmlWebpackInlineSVGPlugin) `HtmlWebpackInlineSVGPlugin` config option?
- Make sure the path to the images is relative to the HTML file on the output folder, not to the project's `package.json`.

If the above wasn't the issue then not sure what could be.

Let's try the next: without the SVG loader and not using the option `runPreEmit` in case you are, could you change the template extension to `*.html`? This should still [fire the default `ejs` loader](https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md#1-dont-set-any-loader) processing the template. But maybe there could be some bug in our plugin where the template code is only processed if the template has `html` extension.

Tony 😀

**Comment by royalrex** [comment]
Hi Tony.

I got it working with the ejs file, your clue about "relative .. in output folder" helped. From the docs, I was trying to get the to work with option 2 "Alternatively use loaders". Still I have no luck.

My original project is angularJS (v1.x). I have tried to set up a repro using latest angular, but my knowledge of angular is not strong enough to figure out what might be the issue with that.

In my original project. When I add the plugin and remove svg extension from my url-loader plugin, everything breaks. In my project I have svgs referenced from my css files and it looks like the css-loader is complaining about inappropriate loader for svg files. 

So to solve that, I have tried adding the file-loader mapped on svg extension.

Now, it started to complain about not being able to find my svg files, moving the file around and trying different paths, I got successful at using an absolute path (/assets/my-file.svg) but the output is not being replaced.

Reference in angular component html file:
```<img src="/img/tests2.svg" inline />```
The file is placed in img folder in the destination directory.
The code being produced is "the same":
```<img src="/img/tests2.svg" inline="">```

Maybe it's something with angular that is breaking things. Will try to setup a minimal angularJS project and see what happens.

Any suggestions are welcome :)

**Comment by AntonioRedondo** [comment]
Let me understand:

1. You were able to get your SVGs inlined when not using loaders.
2. But you need to use the [url-loader](https://webpack.js.org/loaders/url-loader) because it's already part of your AngularJS project setup and used by CSS files.
3. Then you added the file-loader for SVGs files with absolute paths from the project root, but no SVG is inlined.

I think the reason why your SVGs aren't inlined is because the AngularJS templates aren't parsed by `html-webpack-plugin`. That is it, the `template` property only can have an entry point, an `index.html/ejs/whatever` input file. You will need [as many instances of `html-webpack-plugin` as required](https://extri.co/2017/07/11/generating-multiple-html-pages-with-htmlwebpackplugin) on the webpack config to process every single of your AngularJS templates.

Another solution to inline SVGs in AngularJS templates is with the [`ngInclude`](https://docs.angularjs.org/api/ng/directive/ngInclude) directive (more info about this [here](https://stackoverflow.com/questions/28557804/ng-include-tag-and-svg-images-in-angularjs)).

Also possible in Angular 2+ with this other directive: [ng-inline-svg](https://github.com/arkon/ng-inline-svg).

**Comment by AntonioRedondo** [comment]
I hope that you finally made `HtmlWebpackInlineSVGPlugin` working in your project. I'm closing this issue.

**Comment by AntonioRedondo** [comment]
I just saw that maybe another reason why inlining wasn't working was because your were setting `emitFile` to `false`.
